// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalExamCorrection.Models;

public partial class Question
{
    public int QestId { get; set; }

    public string Text { get; set; }

    public string Type { get; set; }

    public int Score { get; set; }

    public string Level { get; set; }

    public int? CrsId { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual Course Crs { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}